services:
  - type: web
    name: findorm-api
    runtime: docker
    dockerfilePath: ./backend/AzeRealtor.Api/Dockerfile
    dockerContext: ./backend/AzeRealtor.Api
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://finddorm.vercel.app
